# Generated by Django 6.1.1 on 2026-09-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_create_default_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='site_url',
            field=models.CharField(max_length=500),
        ),
    ]
